### ISSUE TITLE
Event bus interceptors should allow messages to be sent  without echo

### ISSUE THREAD

**Issue by rajith77** [vert-x3/vertx-amqp-bridge#1]
Currently if I receive a message from an AMQP endpoint and I send it over the event bus to a address, it gets echoed back as all messages 'intercepted'.

We need to find a way for those 'local' messages to avoid being intercepted.

**Comment by purplefox** [comment]
I think this is expected behaviour.

The way I would envision the bridge to be set up is it should only intercept a subset of addresses, e.g. those that begin with "amqp.*" (or whatever), or maybe those that start with "amqp://".

The others it doesn't intercept, then you won't get the "echo".
