### ISSUE TITLE
404 not found : link for referred classes in the Java doc

### ISSUE THREAD

**Issue by ppatierno** [vert-x3/vertx-amqp-bridge#12]
All the class referenced into the Java documentation asciidoc referring to a not existing page (404 not found).

**Comment by gemmellr** [comment]
Thats because the docgen bits generate the links to align with the expected paths on the website. Youll find the same issue with all the modules, not just this one.

**Comment by ppatierno** [comment]
Ah .. ok .. thank @gemmellr ;)
