### ISSUE TITLE
Handling client disconnection

### ISSUE THREAD

**Issue by galves** [vert-x3/vertx-amqp-bridge#13]
How is one meant to handle reconnection if the underlying connection is lost?

Presently I see two issues.

1. AmqpBridgeOptions for reconnection do not seem to work.
2. AmqBridge does not expose any method to manually set a disconnect/exception handler.

This is my current work around but I'm not sure it is closing all open resources fully.

```java
            AmqpBridgeImpl b = (AmqpBridgeImpl) bridge;

            try {
                Field f = b.getClass().getDeclaredField("connection");
                f.setAccessible(true);
                ProtonConnectionImpl protonConnection = (ProtonConnectionImpl) f.get(b);
                f.setAccessible(false);

                protonConnection.disconnectHandler(con -> {
                    logger.error("disconnected");

                    if (producer != null) {
                        producer.end();
                    }
                    connect();
                });
            }
            catch (Exception e) {
                   //NoSuchFieldException
            }
```

**Comment by gemmellr** [comment]
Thanks, this was an oversight. I've added a hook to register a handler to be informed of the connection unexpectedly going away and fixed up the close() to handle the situation too. Your workaround seems fine and essentially equivalent. The reconnect options are coming from the underlying vert.x NetClient and only apply on the initial connection establishment.
