### ISSUE TITLE
Connecting to bad AMQ socket causes Out Of Memory

### ISSUE THREAD

**Issue by galves** [vert-x3/vertx-amqp-bridge#14]
When connecting to an nio socket for example (default tcp 61616 on ActiveMQ), the protocol implementation results in an extremely large buffer allocation, causing the JVM to crash.

**Comment by gemmellr** [comment]
Thanks for reporting. This is an issue in proton-j, I'll take a look over there, and leave this open to track updating to a fixed version.

**Comment by vietj** [comment]
@gemmellr can you fix it for 3.4.0 ?

**Comment by gemmellr** [comment]
@vietj Not without delaying 3.4.0, I'll need to investigate a fix, and then it will need another few days to do a proton-j release containing it.

**Comment by vietj** [comment]
ok, then it will be for 3.4.1!

**Comment by gemmellr** [comment]
I made some changes to vertx-proton via https://github.com/vert-x3/vertx-proton/issues/42 to improve some related behaviour on the vertx side a bit in 3.4.0. The actual issue in proton-j will be fixed next week, folks should be able to adjust their builds to use that version if needed before 3.4.1.

**Comment by gemmellr** [comment]
The update to proton-j 0.18.0 is now in place via https://github.com/vert-x3/vertx-proton/issues/43 and resolves this for 3.4.1 together witih the earlier changes in 3.4.0 mentioned above.
