### ISSUE TITLE
Wrong module status in the documentation

### ISSUE THREAD

**Issue by gualtierotesta** [vert-x3/vertx-amqp-bridge#24]
The documentation (https://vertx.io/docs/vertx-amqp-bridge/java/) is reporting the following:

> Warning: this module has the tech preview status, this means the API can change between versions.

which is not correct.

I believe the message should be the one reported in the README.md file

> NOTE: This component will be removed in Vert.x 4. Consider using either the new vertx-amqp-client or vertx-proton which underpins both.

**Comment by vietj** [comment]
right

**Comment by gemmellr** [comment]
Thanks Julien, I was planning to look at this today and ask if you could publish a site update if there wasn't a 3.8.1 planned that would cause it.

I notice you updated the README as well. It seems 3.7 is still set as the default branch in the repo so folks wont see that update initially.
